apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab-api
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab-api
subjects:
  - kind: ServiceAccount
    name: lab-api
roleRef:
  kind: Role
  name: lab-api
  apiGroup: rbac.authorization.k8s.io
